.TH IFETCH "2009\-02\-03" "0.15.3" "ifetch-tools"

.SH NAME
ifetch \- image collection tool for IP Cameras of ifetch\-tools

.SH SYNOPSIS
\fBifetch\fR \fICONFIG_PATH\fR

.SH DESCRIPTION
ifetch \- image collection tool of ifetch\-tools.
.PP
ifetch\-tools \- A set of tools to collect, monitor, and view images from IP Cameras.

.SH OPTIONS
ifetch \- requires a single option of a camera config file; /etc/ifetch-tools/cameras/camera_num.conf.

.SH HOMEPAGE
More information about ifetch-tools project can be found at <\fIhttp://ifetch-tools.rubyforge.org/\fR>.

.SH AUTHOR
ifetch-tools was written by Richard Nelson <\fIunixabg@gmail.com\fR>.
