.TH WWWIFETCH "2009\-02\-03" "0.15.3" "ifetch-tools"

.SH NAME
wwwifetch \- Web presentation tool of ifetch\-tools

.SH SYNOPSIS
\fBwwwifetch\fR

.SH DESCRIPTION
wwwifetch \- is the presentation layer of ifetch\-tools.
.PP
ifetch\-tools \- A set of tools to collect, monitor, and view images from IP Cameras.

.SH OPTIONS
wwwifetch \- takes no options. See config file in /etc/ifetch-tools/ifetch-tools.conf.

.SH HOMEPAGE
More information about ifetch-tools project can be found at <\fIhttp://ifetch-tools.rubyforge.org/\fR>.

.SH AUTHOR
ifetch-tools was written by Richard Nelson <\fIunixabg@gmail.com\fR>.
